/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tamil.converter;

public class TamilConverter {
    public String convertToTamilScript(String transliteration) {
        if("a".equals(transliteration)){
            return "அ";
        }
        return "இ";
    }
}
