/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tamil.converter;

import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.*;
import static org.hamcrest.Matchers.*;

class TamilConverterTest {

    @Test
    void aConvert() {
        TamilConverter converter = new TamilConverter();
        assertThat(converter.toTamilScript("a"), is("அ"));
    }

    @Test
    void iConvert() {
        TamilConverter converter = new TamilConverter();
        assertThat(converter.toTamilScript("i"), is("இ"));
    }
}
