/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tamil.converter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TamilConverterTest {

    @Test
    void aConvert() {
        TamilConverter converter = new TamilConverter();
        assertEquals("அ", converter.convertToTamilScript("a"));
    }

    @Test
    void iConvert() {
        TamilConverter converter = new TamilConverter();
        assertEquals("இ", converter.convertToTamilScript("i"));
    }
}
